FROM node:20 AS build
WORKDIR /app
COPY /application/package*.json ./
RUN npm install -g @angular/cli && npm install
COPY /application/. .
RUN ng build

FROM debian:bookworm-slim
LABEL maintainer="2210859005@hochschule-burgenland.at"

ENV DEBIAN_FRONTEND=noninteractive
ENV APP_ENV=development

RUN apt update \
 && apt install nginx -y \
 && mv /var/www/html/index.nginx-debian.html /var/www/html/index.html

WORKDIR /var/www/html
COPY --from=build /app/dist/bachelor_project/browser .
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
