FROM debian:bookworm-slim
LABEL maintainer="2210859005@hochschule-burgenland.at"

ENV DEBIAN_FRONTEND=noninteractive
ENV APP_ENV=development

ADD /application/. /usr/src/app

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

RUN apt update && apt install -y curl wget git build-essential \
 && apt update && apt install -y vim nano \
 && curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
 && apt install -y nodejs \
 && node -v && npm -v \
 && npm install -g @angular/cli \
 && npm install \
 && ng build

EXPOSE 4200

CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "4200"]
