FROM debian:bookworm-slim
LABEL maintainer="2210859005@hochschule-burgenland.at"

ENV DEBIAN_FRONTEND=noninteractive
ENV APP_ENV=development

RUN apt update && apt install -y curl wget git build-essential
RUN apt update && apt install -y vim nano

WORKDIR /tmp

RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash -

RUN apt install -y nodejs
 
RUN node -v

RUN npm -v

RUN npm install -g @angular/cli

RUN mkdir -p /usr/src/app

ADD /application/. /usr/src/app

WORKDIR /usr/src/app

RUN npm install

RUN ng build

EXPOSE 4200

CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "4200"]
