FROM node:20 AS build
WORKDIR /app
COPY /application/package*.json ./
RUN npm install -g @angular/cli@19.2.0 && npm ci
COPY /application/. .
RUN ng build

FROM debian:bookworm-slim
LABEL maintainer="2210859005@hochschule-burgenland.at"
ENV DEBIAN_FRONTEND=noninteractive
ENV APP_ENV=development

RUN apt-get update \
 && apt-get install -y nginx-light=1.22.1-9+deb12u1 --no-install-recommends \
 && rm -rf /var/lib/apt/lists/* \
 && mv /var/www/html/index.nginx-debian.html /var/www/html/index.html \
 && groupadd -r user \
 && useradd -r -g user user

WORKDIR /var/www/html
COPY --from=build /app/dist/bachelor_project/browser .
COPY --from=build /app/nginx.conf /etc/nginx/nginx.conf
RUN chown -R user:user /var/www/html \
 && chown -R user:user /etc/nginx
 
USER user
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
